baseURL = 'https://alankr.it/'
theme = 'risotto'
author = 'Alankrit Joshi'
title = 'Alankrit Joshi'

copyright = "© [Alankrit Joshi](https://alankr.it)"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = 'catppuccin-mocha'

[params.about]
title = "Alankrit Joshi"
description = "Software Engineer 🇨🇦 🇮🇳"
# logo_image = "images/profile.svg"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/alankritjoshi"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://linkedin.com/in/alankritjoshi"

[[params.socialLinks]]
icon = "fa fa-file-pdf"
title = "Resume"
url = "https://drive.google.com/open?id=1c-iBFHhmExnyOEDGKVKfonJ_WfTucOGP"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:alankritjoshi@gmail.com"

[menu]

  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "Work"
    name = "Work"
    url = "/work/"
    weight = 10

  [[menu.main]]
    identifier = "Education"
    name = "Education"
    url = "/education/"
    weight = 10

[markup.goldmark.renderer]
unsafe = true

[languages.en]
languageName = "English"

